### ISSUE TITLE
Your External Project ReadMe bash CMake snippets does not work

### ISSUE THREAD

**Issue by petrasvestartas** [intel-isl/Open3D-Example-Project#4]
I am using your CMakeLists file for External Project but I get error attached here:
[CMakeError.log](https://github.com/isl-org/open3d-cmake-external-project/files/8941489/CMakeError.log)
[CMakeOutput.log](https://github.com/isl-org/open3d-cmake-external-project/files/8941490/CMakeOutput.log)

Code:
```
git clone https://github.com/intel-isl/open3d-cmake-external-project.git
cd open3d-cmake-external-project
mkdir build
cd build
cmake ..
cmake --build . --config Release --parallel 12
Release\Draw
```

error happens after build
`cmake --build . --config Release --parallel 12`

![image](https://user-images.githubusercontent.com/18013985/174626379-a677cd1a-ec17-4cf2-9725-6781f7db9fd5.png)

**Comment by zakpr0** [comment]
Hi, try to install nasm from this link
add the exe to ENV PATH and to ASM_NASM 
https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/
